<?php
require('fpdf/fpdf.php');

class PDF extends FPDF{
	function Header(){
		$g[]="A+";
		$g[]="A";
		$g[]="A-";
		$g[]="B";
		$g[]="C";
		$g[]="D";
		$g[]="F";

		$in[]="80-100";
		$in[]="79-70";
		$in[]="60-69";
		$in[]="50-59";
		$in[]="40-49";
		$in[]="33-39";
		$in[]="0-32";

		$p[]="5";
		$p[]="4";
		$p[]="3.5";
		$p[]="3";
		$p[]="2";
		$p[]="1";
		$p[]="0";

    	$this->Ln(5);
	    $this->SetFont('Arial','',8);
	    $this->Cell(150);
	    $this->Cell(15,4,'Grade', 1);
	    $this->Cell(15,4,'Interval', 1);
	    $this->Cell(15,4,'Point', 1);
		$this->Ln();
		for($i=0; $i<count($g); $i++){
		    $this->Cell(150);
			$this->Cell(15,4, ''.$g[$i], 1);
			$this->Cell(15,4, ''.$in[$i], 1);
			$this->Cell(15,4, ''.$p[$i], 1);
			$this->Ln();
		}
	    $this->Ln();
	}
/*	
	function Footer(){
    	$this->SetY(-15);
	    $this->SetFont('Arial','I',8);
	    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
	}*/
}

$pdf=new FPDF('L','mm','A4');
$pdf->AddPage();
$pdf->Header();
// the variables that hopefully generated by quering the database.
$name="Abdullah Al Zakir Hossain";
$fname="Prof. Dr. Mokbul Hossain";
$mname="Mrs. Zakia Hossain";
$sroll="04101009";
$group="CSE";

$subjectname[]="Bangla 1st paper";
$subjectname[]="Bangla 2nd paper";
$subjectname[]="English 1st paper";
$subjectname[]="English 2nd paper";
$subjectname[]="General Math";
$subjectname[]="Religious Studies";
$subjectname[]="General Science";
$subjectname[]="Geography";
$subjectname[]="History";
$subjectname[]="Civics & Economics";
$subjectname[]="Agriculture";
// these should have been taken from database, here I just have generated some example.
for($i=0; $i<count($subjectname); $i++){
	$marks[]="marks ".$i;
	$grade[]="Grade ".$i;
	$gp[]="Grade point ".$i;
	$pgpa[]="Pre GPA ".$i;
	$gpa[]="GPA ".$i;	
}
// End of assigning variables.

// here is the start of printing it in a pdf file.
$pdf->SetFont('Arial', '', 18);
$pdf->Cell(150, 8, 'Collectorate Public School & College, Nilphamari', 0, 1, 'C');
$pdf->SetFont('Arial', '', 14);
$pdf->Cell(150, 10, 'Academic Transcript of 1st Terminal Examination', 0, 1, 'C');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(100, 8, 'Name of Student: '.$name);
$pdf->Ln();
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(100, 8, 'Father Name: '.$fname);
$pdf->Ln();
$pdf->Cell(100, 8, 'Mother Name: '.$mname);
$pdf->Ln();
$pdf->Cell(100, 8, 'Class Roll: '.$sroll);
$pdf->Ln();
$pdf->Cell(100, 8, 'Group: '.$group);
$pdf->Ln();

$pdf->SetFont('Arial', '', 10);
$pdf->Cell(20, 8, 'Serial No.', 1);
$pdf->Cell(40, 8, 'Name of Subjects', 1);
$pdf->Cell(50, 8, 'Marks', 1);
$pdf->Cell(30, 8, 'Grade', 1);
$pdf->Cell(30, 8, 'Grade Point', 1);
$pdf->Cell(30, 8, 'Previous GPA', 1);
$pdf->Cell(30, 8, 'GPA', 1);
$pdf->Ln();

for($i=0; $i<count($subjectname); $i++){
	$pdf->Cell(20, 8, ''.$i+1, 1);
	$pdf->Cell(40, 8, $subjectname[$i], 1);
	$pdf->Cell(50, 8, $marks[$i], 1);
	$pdf->Cell(30, 8, $grade[$i], 1);
	$pdf->Cell(30, 8, $gp[$i], 1);
	$pdf->Cell(30, 8, $pgpa[$i], 1);
	$pdf->Cell(30, 8, $gpa[$i], 1);
	$pdf->Ln();
}
$pdf->Ln();
$pdf->Cell(35, 8, '......................................');
$pdf->Cell(35, 8, 'Signeture');
//End of printing file then the output.

$pdf->Output();
?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Academic Transcript</title>
</head>

<body>
</body>
</html>
